apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc
spec:
  selector:
    app: web
  replicas: 5

  template:
    metadata:
      name: "mypod1"
      labels:
        app: "web"
    spec:
      containers:
      - name: "mycon1"
        image: "vimal13/apache-webserver-php"

